/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
/* Header for class com_axaet_ndk_JniKit */

#ifndef _Included_com_axaet_ndk_JniKit
#define _Included_com_axaet_ndk_JniKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_axaet_ndk_JniKit
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_axaet_ndk_JniKit_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
